### ISSUE TITLE
This should be formatted as a widget

### ISSUE THREAD

**Issue by steveblue** [nmn/famousry#1]
I would have used this in a build had it been written as a famo.us Widget similar to GridView.

**Comment by nmn** [comment]
This was built on an older version of Famo.us, and I'm trying to re-write to make it compatible with the newer version. It will be formatted as a widget soon. Sorry I've been really busy lately.

Another important feature is to seamlessly only render the elements on the screen. I would need to use a viewSequence for that. This is because the performance of the animation drops when the number of elements goes into the 100s.

I'm going to add some features to the repo to understand the interest in various features that I'm trying to add.

**Comment by steveblue** [comment]
No worries, I used famo.us-angular to make a waterfall layout and it works pretty good.
