### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by mkuczera** [nmn/famousry#2]
Hi,
i´m currently working on the same approach of producing a bullet-proof masonry layout with resizing and relayout. Wanted to ask how far you´ve come and if i could help somehow. Famo.us is great, but an elementary layout options like a masonry is not included >.<
hope to hear from you

michael

**Comment by nmn** [comment]
Hi Michael,
I'm sorry, but I've just not had the time to complete famousry.

At the moment, the project is a proof of concept, that shows both that a masonry layout is possible in Famo.us and that it has incredible performance.

It just needs two things to be feasible:
1) As of right now, it doesn't take a list of renderables. This should be fairly trivial to add.
2) As of right now, there is no logic to track the size changes of elements. This again should be trivial with the getSize method of famo.us renderables, but the performance characteristics of that approach are unknown.

Now, if those two things are fixed, the project should technically work, and actually be pretty bullet-proof.

However, the performance may still suffer with a very large number of elements on screen.

Famo.us tends to use the minimum number of surfaces possible. As a result, in a typical famo.us scroll view, there are usually only as many divs as you can see and they are constantly moved around and re-used as you scroll down the page. Famo.us treats DOM elements like RAM.

Famousry, however doesn't do that, and it would be a pretty difficult task to actually make that work. This is predominantly the biggest reason why a masonry layout has not yet been released by famo.us itself.

It's been a long time since I tried to complete famousry. I did this project while I was in famo.us's private beta. I've since not really used Famo.us extensively. I'd love to get back to it and finish it. If you'd like to contribute I'd love some pull requests.

You're also most welcome to fork this project or start another one.
